version: '2.2'

services:

  # browse to: https://localhost:9443/ibmmq/console/
  mqserver:
    image: ibmcom/mq:9.1.5.0-r1
    ports:
      - "1414:1414"
    container_name: mqserver
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    stdin_open: true
    tty: true
    restart: always